"""Added owner in SetMeeting Class

Revision ID: 955734f0fd23
Revises: 
Create Date: 2023-12-07 17:00:53.430194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955734f0fd23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_meeting', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
